baseURL = "https://nathanpetersen.com"

custom_css = ["css/custom.css"]

# Change the default theme to be use when building the site with Hugo
theme = "myLoveIt"

# website title
title = "Nathan Petersen"

languageCode = "en-us"
languageName = "English"

# Author config
[author]
  name = "Nathan Petersen"
  email = ""
  link = "https://nathanpetersen.com/"

[permalinks]
  posts = '/:year/:month/:day/:title/'

# Menu config
[menu]
  [[menu.main]]
    weight = 1
    identifier = "bio"
    name = "Bio"
    url = "/bio/"
  [[menu.main]]
    weight = 2
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
  [[menu.main]]
    weight = 3
    identifier = "categories"
    name = "Categories"
    url = "/categories/"
  [[menu.main]]
    weight = 4
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
  [[menu.main]]
    weight = 5
    identifier = "photography"
    name = "Photography"
    url = "/photography/"
  [[menu.main]]
    weight = 6
    identifier = "contact"
    name = "Contact"
    url = "/contact/"

# Markup related configuration in Hugo
[markup]
  # Syntax Highlighting (https://gohugo.io/content-management/syntax-highlighting)
  [markup.highlight]
    # false is a necessary configuration (https://github.com/dillonzq/LoveIt/issues/158)
    noClasses = false

[params]
  # site default theme ["auto", "light", "dark"]
  defaultTheme = "auto"

  dateformat = "January 2, 2006"

  [params.math]
    enable = true
    copyTex = true

  # Header config
  [params.header]
    [params.header.title]
      logo = "/images/n.png"
      name = "Nathan Petersen"

  # Footer config
  [params.footer]
    enable = true
    hugo = false
    copyright = true
    author = true
    since = 2016
    license = 'Content is licensed under <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank" rel="license noopener noreferrer">CC BY-NC-SA 4.0</a> unless indicated'

  # Home page config
  [params.home]
    # Home page profile
    [params.home.profile]
      enable = true
      avatarURL = "/images/nathan.jpg"
      title = "Nathan Petersen"
      subtitle = "Research of control methods for magnetically levitated motors."
      typeit = false
      social = true
      disclaimer = "Nathan is currently pursuing a PhD at the <a href='https://www.wisc.edu/'>University of Wisconsin–Madison</a> studying <a href='https://engineering.wisc.edu/departments/electrical-computer-engineering/'>Electrical Engineering</a> with emphasis on control of electric machines. He is a student member of the <a href='https://wempec.wisc.edu/'>Wisconsin Electric Machines and Power Electronics Consortium (WEMPEC)</a>."
    
    # Home page posts
    [params.home.posts]
      enable = false

  [params.section]
    paginate = 20
    dateFormat = "Jan 2"
    rss = 10

  [params.list]
    paginate = 20
    dateFormat = "Jan 2"
    rss = 10

  # Social config about the author
  [params.social]
    GitHub = "npetersen2"
    Linkedin = "nathanpetersenn"
    Stackoverflow = ""
    Spotify = "1255332295"
    Googlescholar = "oan5hE4AAAAJ"
    #Email = "nathan.petersen@wisc.edu"
    RSS = true