name: Hugo Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
      with:
        # Number of commits to fetch. 0 indicates all history for all branches and tags.
        fetch-depth: '0'
        submodules: 'recursive'
        
    - name: Install Hugo packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade -y
        sudo apt-get install hugo
    
    - name: Check hugo version
      run: hugo version

    - name: Build website
      run: hugo

    # Publish built docs to gh-pages branch.
    # ===============================
    - name: Commit website changes
      run: |
        rm -rf docs # not sure if this is needed...
        mkdir docs
        cp -rf public/* docs/
        cd docs
        echo "nathanpetersen.com" > CNAME
        touch .nojekyll # need this due to "_*" dirs getting ignored by GitHub
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Update website" -a || true
        # The above command will fail if no changes were present, so we ignore that.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        force: true
        directory: docs
        github_token: ${{ secrets.GITHUB_TOKEN }}
    # ===============================
